'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleados
    Public Property dpi_emp As Long
    Public Property nombre_emp As String
    Public Property hijos_emp As Nullable(Of Integer)
    Public Property salariobase_emp As Nullable(Of Double)
    Public Property bono_emp As Nullable(Of Double)
    Public Property creacion_emp As Nullable(Of Date)
    Public Property iggs_emp As Nullable(Of Double)
    Public Property irtra_emp As Nullable(Of Double)
    Public Property bonopater_emp As Nullable(Of Double)
    Public Property salario_total_emp As Nullable(Of Double)
    Public Property salario_liquido_emp As Nullable(Of Double)

End Class
